### ISSUE TITLE
document API

### ISSUE THREAD

**Issue by bcoe** [istanbuljs/istanbul-lib-report#1]
@gotwarlost could you provide a gist with a basic idea of how I'd swap out the old istanbul report API for this one, I'm looking at switching `nyc` over to this API. Specifically:
- how do I use it in conjunction with the reports repo?
- is there a way to run multiple reports at once, as with the old API.

**Comment by bcoe** [comment]
this approach seemed to work, am I on the right track?

``` js
  var context = libReport.createContext()
  var tree = libReport.summarizers.pkg(map)
  var report = reports.create('text')

  this._loadReports().forEach(function (report) {
    map.merge(report)
  })

  tree.visit(report, context)
```

**Comment by gotwarlost** [comment]
That seems right. I don't have access to the code right now - will take s closer look after 6 hours or so.
